[spotifywmSrc]
src.git = "https://github.com/dasJ/spotifywm"
fetch.git = "https://github.com/dasJ/spotifywm"

[officialThemes]
src.git = "https://github.com/spicetify/spicetify-themes"
fetch.git = "https://github.com/spicetify/spicetify-themes"

[officialSrc]
src.git = "https://github.com/spicetify/spicetify-cli"
fetch.git = "https://github.com/spicetify/spicetify-cli"
 
[hazySrc]
src.git = "https://github.com/Astromations/Hazy"
fetch.git = "https://github.com/Astromations/Hazy"

[dakshExtensions]
src.git = "https://github.com/daksh2k/Spicetify-stuff"
fetch.git = "https://github.com/daksh2k/Spicetify-stuff"

[hidePodcastsSrc]
src.git = "https://github.com/theRealPadster/spicetify-hide-podcasts"
fetch.git = "https://github.com/theRealPadster/spicetify-hide-podcasts"

[localFilesSrc]
src.git = "https://github.com/hroland/spicetify-show-local-files"
fetch.git = "https://github.com/hroland/spicetify-show-local-files"

[customAppsExtensionsSrc]
src.git = "https://github.com/3raxton/spicetify-custom-apps-and-extensions"
fetch.git = "https://github.com/3raxton/spicetify-custom-apps-and-extensions"

[charlieS1103Src]
src.git = "https://github.com/CharlieS1103/spicetify-extensions"
fetch.git = "https://github.com/CharlieS1103/spicetify-extensions"

[huhExtensionsSrc]
src.git = "https://github.com/huhridge/huh-spicetify-extensions"
fetch.git = "https://github.com/huhridge/huh-spicetify-extensions"

[nameThatTuneSrc]
src.git = "https://github.com/theRealPadster/name-that-tune"
src.branch = "dist"
fetch.git = "https://github.com/theRealPadster/name-that-tune"

[marketplaceSrc]
src.git = "https://github.com/spicetify/spicetify-marketplace"
src.branch = "dist"
fetch.git = "https://github.com/spicetify/spicetify-marketplace"
