[spotifywmSrc]
src.git = "https://github.com/dasJ/spotifywm"
fetch.git = "https://github.com/dasJ/spotifywm"

[officialThemes]
src.git = "https://github.com/spicetify/spicetify-themes"
fetch.git = "https://github.com/spicetify/spicetify-themes"

[officialSrc]
src.git = "https://github.com/spicetify/spicetify-cli"
fetch.git = "https://github.com/spicetify/spicetify-cli"
 
[hazySrc]
src.git = "https://github.com/Astromations/Hazy"
fetch.git = "https://github.com/Astromations/Hazy"

[dakshExtensionsSrc]
src.git = "https://github.com/daksh2k/Spicetify-stuff"
fetch.git = "https://github.com/daksh2k/Spicetify-stuff"

[hidePodcastsSrc]
src.git = "https://github.com/theRealPadster/spicetify-hide-podcasts"
fetch.git = "https://github.com/theRealPadster/spicetify-hide-podcasts"

[customAppsExtensionsSrc]
src.git = "https://github.com/3raxton/spicetify-custom-apps-and-extensions"
fetch.git = "https://github.com/3raxton/spicetify-custom-apps-and-extensions"

[rxriSrc]
src.git = "https://github.com/rxri/spicetify-extensions"
fetch.git = "https://github.com/rxri/spicetify-extensions"

[huhExtensionsSrc]
src.git = "https://github.com/huhridge/huh-spicetify-extensions"
fetch.git = "https://github.com/huhridge/huh-spicetify-extensions"