[spotifywmSrc]
src.git = "https://github.com/dasJ/spotifywm"
fetch.git = "https://github.com/dasJ/spotifywm"

[officialThemes]
src.git = "https://github.com/spicetify/spicetify-themes"
fetch.git = "https://github.com/spicetify/spicetify-themes"

[officialSrc]
src.git = "https://github.com/spicetify/spicetify-cli"
fetch.git = "https://github.com/spicetify/spicetify-cli"

[dakshExtensions]
src.git = "https://github.com/daksh2k/Spicetify-stuff"
fetch.git = "https://github.com/daksh2k/Spicetify-stuff"

[hidePodcastsSrc]
src.git = "https://github.com/theRealPadster/spicetify-hide-podcasts"
fetch.git = "https://github.com/theRealPadster/spicetify-hide-podcasts"

[historySrc]
src.git = "https://github.com/einzigartigerName/spicetify-history"
fetch.git = "https://github.com/einzigartigerName/spicetify-history"

[lastfmSrc]
src.git = "https://github.com/LucasBares/spicetify-last-fm"
fetch.git = "https://github.com/LucasBares/spicetify-last-fm"

[localFilesSrc]
src.git = "https://github.com/hroland/spicetify-show-local-files"
fetch.git = "https://github.com/hroland/spicetify-show-local-files"

[autoVolumeSrc]
src.git = "https://github.com/amanharwara/spicetify-autoVolume"
fetch.git = "https://github.com/amanharwara/spicetify-autoVolume"

[customAppsExtensionsSrc]
src.git = "https://github.com/3raxton/spicetify-custom-apps-and-extensions"
fetch.git = "https://github.com/3raxton/spicetify-custom-apps-and-extensions"

[charlieS1103Src]
src.git = "https://github.com/CharlieS1103/spicetify-extensions"
fetch.git = "https://github.com/CharlieS1103/spicetify-extensions"

[huhExtensionsSrc]
src.git = "https://github.com/huhridge/huh-spicetify-extensions"
fetch.git = "https://github.com/huhridge/huh-spicetify-extensions"

[playlistIconsSrc]
src.git = "https://github.com/jeroentvb/spicetify-playlist-icons"
src.branch = "dist"
fetch.git = "https://github.com/jeroentvb/spicetify-playlist-icons"

[tetraxSrc]
src.git = "https://github.com/Tetrax-10/Spicetify-Extensions"
fetch.git = "https://github.com/Tetrax-10/Spicetify-Extensions"

[powerBarSrc]
src.git = "https://github.com/jeroentvb/spicetify-power-bar"
src.branch = "dist"
fetch.git = "https://github.com/jeroentvb/spicetify-power-bar"

[groupSessionSrc]
src.git = "https://github.com/timll/spotify-group-session"
fetch.git = "https://github.com/timll/spotify-group-session"

[startPageSrc]
src.git = "https://github.com/Resxt/startup-page"
fetch.git = "https://github.com/Resxt/startup-page"

[nameThatTuneSrc]
src.git = "https://github.com/theRealPadster/name-that-tune"
src.branch = "dist"
fetch.git = "https://github.com/theRealPadster/name-that-tune"

[marketplaceSrc]
src.git = "https://github.com/spicetify/spicetify-marketplace"
src.branch = "dist"
fetch.git = "https://github.com/spicetify/spicetify-marketplace"
