# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  customAppsExtensionsSrc = {
    pname = "customAppsExtensionsSrc";
    version = "0f5e79fe43abf57f714d7d00bd288870d5b6f718";
    src = fetchgit {
      url = "https://github.com/3raxton/spicetify-custom-apps-and-extensions";
      rev = "0f5e79fe43abf57f714d7d00bd288870d5b6f718";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-4zL/z8dCafy5V95ASR3c6TffMh9wdpnclAjddD9TX84=";
    };
    date = "2022-05-02";
  };
  dakshExtensionsSrc = {
    pname = "dakshExtensionsSrc";
    version = "232b892f2ba415152dff8060f83ecc2f704a3371";
    src = fetchgit {
      url = "https://github.com/daksh2k/Spicetify-stuff";
      rev = "232b892f2ba415152dff8060f83ecc2f704a3371";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-J0VytMVP+leLmHyC5Ws+k0Ed3jZHcm0RVeZ95kaFy70=";
    };
    date = "2024-07-21";
  };
  hazySrc = {
    pname = "hazySrc";
    version = "2fe1599e18cd0bfac02f8a846772574f5059715b";
    src = fetchgit {
      url = "https://github.com/Astromations/Hazy";
      rev = "2fe1599e18cd0bfac02f8a846772574f5059715b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-OAdBVIgtmMvUm66FI+Ls0YobkPVg67W3Up+AIFr5rhw=";
    };
    date = "2024-07-26";
  };
  hidePodcastsSrc = {
    pname = "hidePodcastsSrc";
    version = "a0752e5ef6f7bfd7399a0a795a437c0b398246ba";
    src = fetchgit {
      url = "https://github.com/theRealPadster/spicetify-hide-podcasts";
      rev = "a0752e5ef6f7bfd7399a0a795a437c0b398246ba";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-mxodEgw0BaeRJri/2z9fmrFNCSE9soB1wV9uTGnGkWM=";
    };
    date = "2024-08-02";
  };
  huhExtensionsSrc = {
    pname = "huhExtensionsSrc";
    version = "f032dde7cce9d441795d9e2f728531684e97e3fa";
    src = fetchgit {
      url = "https://github.com/huhridge/huh-spicetify-extensions";
      rev = "f032dde7cce9d441795d9e2f728531684e97e3fa";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-fttZYeWqGNy4A9FqHe8znaWGePI2bBE92Ir4bp3i1wY=";
    };
    date = "2023-12-06";
  };
  officialSrc = {
    pname = "officialSrc";
    version = "f564dfe46388c3ea75a8de407723ab83def66925";
    src = fetchgit {
      url = "https://github.com/spicetify/spicetify-cli";
      rev = "f564dfe46388c3ea75a8de407723ab83def66925";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-8dLWOJv1bBzPxvxYEjwtm8wfnfHmHmg1gAnrZl+T3YQ=";
    };
    date = "2024-08-03";
  };
  officialThemes = {
    pname = "officialThemes";
    version = "37c6348144a24bcdd5b554ed765a691fb33eece4";
    src = fetchgit {
      url = "https://github.com/spicetify/spicetify-themes";
      rev = "37c6348144a24bcdd5b554ed765a691fb33eece4";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-JmH0oREsNMwtAIBb7OvSTt6FRpX1gjK3RptE1rrXWEg=";
    };
    date = "2024-08-01";
  };
  rxriSrc = {
    pname = "rxriSrc";
    version = "e287557c119f7962383ca4c41caadd7329211a55";
    src = fetchgit {
      url = "https://github.com/rxri/spicetify-extensions";
      rev = "e287557c119f7962383ca4c41caadd7329211a55";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-G1BnYfUVBChIZQRpnOm6befMw0q/q7oyvsawDKoL4Pw=";
    };
    date = "2024-07-18";
  };
  spotifywmSrc = {
    pname = "spotifywmSrc";
    version = "8624f539549973c124ed18753881045968881745";
    src = fetchgit {
      url = "https://github.com/dasJ/spotifywm";
      rev = "8624f539549973c124ed18753881045968881745";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-AsXqcoqUXUFxTG+G+31lm45gjP6qGohEnUSUtKypew0=";
    };
    date = "2022-10-25";
  };
}
