# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  customAppsExtensionsSrc = {
    pname = "customAppsExtensionsSrc";
    version = "0f5e79fe43abf57f714d7d00bd288870d5b6f718";
    src = fetchgit {
      url = "https://github.com/3raxton/spicetify-custom-apps-and-extensions";
      rev = "0f5e79fe43abf57f714d7d00bd288870d5b6f718";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-4zL/z8dCafy5V95ASR3c6TffMh9wdpnclAjddD9TX84=";
    };
    date = "2022-05-02";
  };
  dakshExtensionsSrc = {
    pname = "dakshExtensionsSrc";
    version = "e16e54e8463270e636ba4353170b222e10661600";
    src = fetchgit {
      url = "https://github.com/daksh2k/Spicetify-stuff";
      rev = "e16e54e8463270e636ba4353170b222e10661600";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-ksTCISkR7BADA8TWJCmmw7IupEC1q5RIijk9rzhXGN8=";
    };
    date = "2024-06-05";
  };
  hazySrc = {
    pname = "hazySrc";
    version = "0d45831a31b0c72e1d3ab8be501479e196a709d7";
    src = fetchgit {
      url = "https://github.com/Astromations/Hazy";
      rev = "0d45831a31b0c72e1d3ab8be501479e196a709d7";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-0t7/25hRfvyJ8K+nTzgMl8RabTBxtMIjQvDECzYvwg8=";
    };
    date = "2024-06-02";
  };
  hidePodcastsSrc = {
    pname = "hidePodcastsSrc";
    version = "4b4d39842088ca4717166a04e914b338ea5a8680";
    src = fetchgit {
      url = "https://github.com/theRealPadster/spicetify-hide-podcasts";
      rev = "4b4d39842088ca4717166a04e914b338ea5a8680";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-o62evqPjxKwJTpJsRM+9F1cuGLpIyy07tf5aO8KxNk8=";
    };
    date = "2024-05-01";
  };
  huhExtensionsSrc = {
    pname = "huhExtensionsSrc";
    version = "f032dde7cce9d441795d9e2f728531684e97e3fa";
    src = fetchgit {
      url = "https://github.com/huhridge/huh-spicetify-extensions";
      rev = "f032dde7cce9d441795d9e2f728531684e97e3fa";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-fttZYeWqGNy4A9FqHe8znaWGePI2bBE92Ir4bp3i1wY=";
    };
    date = "2023-12-06";
  };
  officialSrc = {
    pname = "officialSrc";
    version = "c1493ae64f5f0f83201fde6413019e864ff09425";
    src = fetchgit {
      url = "https://github.com/spicetify/spicetify-cli";
      rev = "c1493ae64f5f0f83201fde6413019e864ff09425";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-s+arCV5O8EaheJSlRCXxWqIwSPZ2SfRWKVFnYTgBYIQ=";
    };
    date = "2024-06-13";
  };
  officialThemes = {
    pname = "officialThemes";
    version = "dfdd89ad84d5c68915c65e4a83580047349c49b4";
    src = fetchgit {
      url = "https://github.com/spicetify/spicetify-themes";
      rev = "dfdd89ad84d5c68915c65e4a83580047349c49b4";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-8IF2Y7xJtzk92rl4bfjiMXCISzUMaxXxOaMZkLS5mww=";
    };
    date = "2024-05-17";
  };
  rxriSrc = {
    pname = "rxriSrc";
    version = "9168bc5d6c3b816ba404d91161fd577b3bf43e4a";
    src = fetchgit {
      url = "https://github.com/rxri/spicetify-extensions";
      rev = "9168bc5d6c3b816ba404d91161fd577b3bf43e4a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-kPjmDVyxtXG1puedQKD6HRP6eN/MPdEZ9Zs4Ao4RVtg=";
    };
    date = "2024-06-14";
  };
  spotifywmSrc = {
    pname = "spotifywmSrc";
    version = "8624f539549973c124ed18753881045968881745";
    src = fetchgit {
      url = "https://github.com/dasJ/spotifywm";
      rev = "8624f539549973c124ed18753881045968881745";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-AsXqcoqUXUFxTG+G+31lm45gjP6qGohEnUSUtKypew0=";
    };
    date = "2022-10-25";
  };
}
