# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  customAppsExtensionsSrc = {
    pname = "customAppsExtensionsSrc";
    version = "0f5e79fe43abf57f714d7d00bd288870d5b6f718";
    src = fetchgit {
      url = "https://github.com/3raxton/spicetify-custom-apps-and-extensions";
      rev = "0f5e79fe43abf57f714d7d00bd288870d5b6f718";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-4zL/z8dCafy5V95ASR3c6TffMh9wdpnclAjddD9TX84=";
    };
    date = "2022-05-02";
  };
  dakshExtensionsSrc = {
    pname = "dakshExtensionsSrc";
    version = "f78c04e13fbbcae2db654dd69c314aa9101a7340";
    src = fetchgit {
      url = "https://github.com/daksh2k/Spicetify-stuff";
      rev = "f78c04e13fbbcae2db654dd69c314aa9101a7340";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-O7Y3Ac5rU9DaNJlZsyRbdJfjwBE5tjpzOeQotfLg9zk=";
    };
    date = "2024-06-29";
  };
  hazySrc = {
    pname = "hazySrc";
    version = "0f10b520d94ad84b2d0f6fbee31277ce3212ff4e";
    src = fetchgit {
      url = "https://github.com/Astromations/Hazy";
      rev = "0f10b520d94ad84b2d0f6fbee31277ce3212ff4e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-DpBRfNDMryCmpqJC2PW43XOXrw0wQhcsIocCNRZWM0Q=";
    };
    date = "2024-06-30";
  };
  hidePodcastsSrc = {
    pname = "hidePodcastsSrc";
    version = "30b164971c3d49ac456040269a2263e843ad1f7d";
    src = fetchgit {
      url = "https://github.com/theRealPadster/spicetify-hide-podcasts";
      rev = "30b164971c3d49ac456040269a2263e843ad1f7d";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-N8hBKMEQwz77dnAKKvTP20tW+D8P+K5l19SDkz8CGYg=";
    };
    date = "2024-07-06";
  };
  huhExtensionsSrc = {
    pname = "huhExtensionsSrc";
    version = "f032dde7cce9d441795d9e2f728531684e97e3fa";
    src = fetchgit {
      url = "https://github.com/huhridge/huh-spicetify-extensions";
      rev = "f032dde7cce9d441795d9e2f728531684e97e3fa";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-fttZYeWqGNy4A9FqHe8znaWGePI2bBE92Ir4bp3i1wY=";
    };
    date = "2023-12-06";
  };
  officialSrc = {
    pname = "officialSrc";
    version = "7a2fc97d6546e594fb3c24453f369143e86ecf00";
    src = fetchgit {
      url = "https://github.com/spicetify/spicetify-cli";
      rev = "7a2fc97d6546e594fb3c24453f369143e86ecf00";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Ribm13/3xV2a4EaWt3ZDkXxIdR4O8H0X9uNW6+eEZVo=";
    };
    date = "2024-07-10";
  };
  officialThemes = {
    pname = "officialThemes";
    version = "36f6921ca7c6aa5b7a9722875e143c6d24677946";
    src = fetchgit {
      url = "https://github.com/spicetify/spicetify-themes";
      rev = "36f6921ca7c6aa5b7a9722875e143c6d24677946";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-R8sDc2khi2bUEV4hqxEHNc2i0270jYXI9WSfxYufKO4=";
    };
    date = "2024-07-09";
  };
  rxriSrc = {
    pname = "rxriSrc";
    version = "4c692375d2fc0909b7b068466cedd24ec59408cb";
    src = fetchgit {
      url = "https://github.com/rxri/spicetify-extensions";
      rev = "4c692375d2fc0909b7b068466cedd24ec59408cb";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-/23lKBXL+SBjVhkQnsboxpZ1KpunjEeUbqbhrBQ9RgU=";
    };
    date = "2024-07-06";
  };
  spotifywmSrc = {
    pname = "spotifywmSrc";
    version = "8624f539549973c124ed18753881045968881745";
    src = fetchgit {
      url = "https://github.com/dasJ/spotifywm";
      rev = "8624f539549973c124ed18753881045968881745";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-AsXqcoqUXUFxTG+G+31lm45gjP6qGohEnUSUtKypew0=";
    };
    date = "2022-10-25";
  };
}
